from pydantic import BaseModel, Field, ConfigDict, AliasChoices
from typing import Optional, Literal, List
from uuid import uuid4

from open_aglabs.core.base_models import MLOutput, Location, Notes, AgronomicProperties, TrialProperties, ProtocolProperties
from open_aglabs.core.constants import CROP_LIST, SOIL_COLOR, IMAGE_TYPE_LIST, ORIENTATION_LIST


class CameraProperties(BaseModel):
    """
    Values to support the proper documentation of camera, if you add information to this json please update this doc. https://docs.google.com/spreadsheets/d/1zljGA5xtwtLNXqjohfXeJzh6SFwdObAjmb5gHflQfIA/edit?gid=1769639569#gid=1769639569
    """
    make: Optional[float] = Field(
        None,
        description="The make (manufacturer) of the camera, represented as a number."
    )
    model: Optional[str] = Field(
        None,
        description="The model of the camera."
    )
    iso: Optional[float] = Field(
        None,
        description="The iso setting of the camera."
    )
    magnification: Optional[float] = Field(
        None,
        description="The magnification setting of the camera."
    )
    model_config = ConfigDict(
        extra='forbid'
    )


class AcquisitionProperties(BaseModel):
    """
    All the approved values to be captured about Images of Ag Data.
    """
    date: Optional[str] = Field(
        None,
        description="The date the image was taken"
    )
    time: Optional[str] = Field(
        None,
        description="The time the image was taken"
    )
    camera_height_m: Optional[float] = Field(
        None,
        description="The height of the camera in meters",
        ge=0
    )
    camera_angle_deg: Optional[float] = Field(
        None,
        ge=0,
        description="The angle of the camera when the photo was taken"
    )
    object_resolution: Optional[str] = Field(
        None,
        description="Image Level / Collection Level depending on variance."
    )
    object_resolution_ml: Optional[MLOutput] = Field(
        None,
        description="The resolution of the object in the image predicted by a ML model."
    )
    light_source: Optional[str] = Field(
        None,
        description="What light source was used to collect the image."
    )
    lighting_lux: Optional[float] = Field(
        None,
        ge=0,
        le=100000,
        description="The amount of Lux being generated by a sutnetic light source or measured by a lux meter."

    )
    setting: Optional[str] = Field(
        None,
        description="Where was the image taken"
    )

    model_config = ConfigDict(
        extra='forbid'
    )


class ImageQuality(BaseModel):
    """
    The properties associated with Image Quality
    """
    exposure: Optional[float] = Field(
        None,
        description="The exposure of the image.",
        ge=1,
        le=100
    )
    aperture: Optional[str] = Field(
        None,
        description="The Aperture of the camera when the image was taken."
    )
    iso: Optional[float] = Field(
        None,
        description="The ISO value when the image was taken",
        ge=0,
        le=100000
    )
    height: Optional[float] = Field(
        None,
        description="The height of the image in pixels.",
        ge=0,
        le=100000
    )
    width: Optional[float] = Field(
        None,
        description="The width of the image in pixels",
        ge=0,
        le=100000
    )
    est_gsd_mm: Optional[float] = Field(
        None,
        description="The estimated ground sample distance of the image in mm.",
        gt=0
    )
    orientation: Optional[Literal[*ORIENTATION_LIST]] = Field(
        None,
        description="The orientation of the image.",
    )
    channels: Optional[float] = Field(
        None,
        description="The number of channels in the image.",
        ge=1,
    )
    blur_score: Optional[MLOutput] = Field(
        None
    )
    pct_pixel_over_saturation: Optional[float] = Field(
        None,
        description="The percentage of pixels that were over saturated.",
        ge=0,
        le=100
    )
    pct_pixel_under_saturation: Optional[float] = Field(
        None,
        description="The percentage of pixels that were under saturated.",
        ge=0,
        le=100
    )

    model_config = ConfigDict(
        extra='forbid'
    )


class SyntheticImageProperties(BaseModel):
    """
    Values associated with Synthetic Images
    """
    model: Optional[str] = Field(
        None,
        description="The model of the synthetic image."
    )
    seed: Optional[int] = Field(
        None,
        description="The seed used to generate the synthetic image."
    )
    noise: Optional[float] = Field(
        None,
    )
    model_config = ConfigDict(
        extra='allow'
    )


class AgImageModel(BaseModel):
    """
    All the approved values to be captured about Images of Ag Data.
    """
    path: Optional[str] = Field(
        None,
        description="The path to the image"
    )
    id: str = Field(
        ...,
        validation_alias=AliasChoices('image_id', 'id'),
        description="The Unique ID of the image, should be the image name, by default UUID4."
    )
    device: Optional[str] = Field(
        None,
        description="The type of device that is collecting the images, mobile, auxillery, or drone."
    )
    type: Optional[Literal[*IMAGE_TYPE_LIST]] = Field(
        None,
        description="The type of image it is: original, augmented, synthetic."
    )
    protocol_properties: Optional[ProtocolProperties] = Field(
        None
    )
    trial_properties: Optional[TrialProperties] = Field(
        None
    )
    camera_properties: Optional[CameraProperties] = Field(
        None
    )
    location_properties: Optional[Location] = Field(
        None
    )
    acquisition_properties: Optional[AcquisitionProperties] = Field(
        None
    )
    image_quality: Optional[ImageQuality] = Field(
        None
    )
    agronomic_properties: Optional[AgronomicProperties] = Field(
        None
    )
    synthetic_image_properties: Optional[SyntheticImageProperties] = Field(
        None
    )
    notes: Optional[List[Notes]] = Field(
        None
    )

    model_config = ConfigDict(
        extra='allow',
        json_schema_extra={
            "example": {
                "path": "/images/field_A/row_1/image_001.jpg",
                "id": str(uuid4()),
                "device": "drone",
                "type": "original",
                "camera_properties": {
                    "model": "DJI Mavic 2 Pro",
                    "make": 1.0,
                    "iso": 100.0,
                    "magnification": 1.0
                },
                "location_properties": {
                    "latitude": 34.0522,
                    "longitude": -118.2437,
                    "elevation_m": 100.5,
                    "crs": "EPSG:4326",
                    "country": "USA",
                    "state": "California",
                    "county": "Los Angeles"
                },
                "protocol_properties": {
                    "name": "Drone Survey v1.0",
                    "id": "corn field",
                    "url": None
                },
                "trial_properties": {
                    'name': 'breeding_a'
                },
                "acquisition_properties": {
                    "date": "2025-09-30",
                    "time": "10:30:00",
                    "camera_height_m": 50.0,
                    "camera_angle_deg": 0.0,
                    "object_resolution": "high",
                    "object_resolution_ml": {
                        "pred": 0.05,
                        "model_version": "v1.0"
                    },
                    "light_source": "sunlight",
                    "lighting_lux": 50000.0,
                    "setting": "outdoor"
                },
                "image_quality": {
                    "exposure": 50.0,
                    "aperture": "f/2.8",
                    "iso": 100.0,
                    "height": 4000.0,
                    "width": 6000.0,
                    "channels": 3,
                    "blur_score": {
                        "pred": 2.5,
                        "model": "blur_detector_v1"
                    },
                    "pct_pixel_over_saturation": 1.2,
                    "pct_pixel_under_saturation": 0.5
                },
                "agronomic_properties": {
                    "crop_type": "corn",
                    "growth_stage": "V6",
                    "soil_color": "dark",
                    "weed_pressure": "low",
                    "irrigation_level": "standard",
                    "tillage_type": "no-till",
                    "fertilizer_level": "standard"
                },
                "synthetic_image_properties": {
                    "model": 'v1',
                    "seed": 12345,
                    "noise": 0.01,
                }
            }
        }
    )
