from pydantic import BaseModel, Field, ConfigDict, AliasChoices
from typing import Optional, Literal, List

from open_aglabs.core.base_models import MLOutput, Location, Notes, AgronomicProperties, TrialProperties, \
    ProtocolProperties, CollectionProperties
from open_aglabs.core.constants import CROP_LIST, SOIL_COLOR, IMAGE_TYPE_LIST, ORIENTATION_LIST


class CameraProperties(BaseModel):
    """
    Values to support the proper documentation of camera, if you add information to this json please update this doc. https://docs.google.com/spreadsheets/d/1zljGA5xtwtLNXqjohfXeJzh6SFwdObAjmb5gHflQfIA/edit?gid=1769639569#gid=1769639569
    """
    make: Optional[str] = Field(
        None,
        description="The make (manufacturer) of the camera, represented as a str."
    )
    model: Optional[str] = Field(
        None,
        description="The model of the camera."
    )
    device_id: Optional[str] = Field(
        None,
        validation_alias=AliasChoices('deviceID', 'device_id'),
        description="Unique persistent CPU ID or collection ID."
    )
    device_specification: Optional[str] = Field(
        None,
        description="Phone model question/specification string (e.g., Manufacturer=samsung, Model=SM-A556E). IF Device is Mobile"
    )
    camera_characteristics: Optional[str] = Field(
        None,
        description="Camera characteristics (e.g., focal length, sensor size, lens type)."
    )
    iso: Optional[float] = Field(
        None,
        description="The iso setting of the camera."
    )
    magnification: Optional[float] = Field(
        None,
        description="The magnification setting of the camera."
    )
    model_config = ConfigDict(
        extra='forbid'
    )


class AcquisitionProperties(BaseModel):
    """
    All the approved values to be captured about Images of Ag Data.
    """
    date: Optional[str] = Field(
        None,
        description="The date the image was taken"
    )
    time: Optional[str] = Field(
        None,
        description="The time the image was taken"
    )
    camera_height_m: Optional[float] = Field(
        None,
        description="The height of the camera in meters",
        ge=0
    )
    camera_angle_deg: Optional[float] = Field(
        None,
        ge=-180,
        le=180,
        description="The angle of the camera when the photo was taken"
    )
    azimuth: Optional[float] = Field(
        None,
        ge=-180,
        le=180,
        description=""
    )
    pitch: Optional[float] = Field(
        None,
        ge=-180,
        le=180,
        description=""
    )
    roll: Optional[float] = Field(
        None,
        ge=-180,
        le=180,
        description=""
    )
    object_resolution: Optional[str] = Field(
        None,
        description="Image Level / Collection Level depending on variance."
    )
    object_resolution_ml: Optional[MLOutput] = Field(
        None,
        description="The resolution of the object in the image predicted by a ML model."
    )
    light_source: Optional[str] = Field(
        None,
        description="What light source was used to collect the image."
    )
    lighting_lux: Optional[float] = Field(
        None,
        ge=0,
        le=100000,
        description="The amount of Lux being generated by a sutnetic light source or measured by a lux meter."
    )
    setting: Optional[str] = Field(
        None,
        description="Where was the image taken"
    )

    model_config = ConfigDict(
        extra='forbid'
    )


class ImageQuality(BaseModel):
    """
    The properties associated with Image Quality
    """
    capture_results: Optional[str] = Field(
        None,
        description="The results of the capture process."
    )
    exposure: Optional[float] = Field(
        None,
        description="The exposure of the image.",
        ge=0,
        le=100
    )
    aperture: Optional[str] = Field(
        None,
        description="The Aperture of the camera when the image was taken."
    )
    iso: Optional[float] = Field(
        None,
        description="The ISO value when the image was taken",
        ge=0,
        le=100000
    )
    height: Optional[float] = Field(
        None,
        description="The height of the image in pixels.",
        ge=0,
        le=100000
    )
    width: Optional[float] = Field(
        None,
        description="The width of the image in pixels",
        ge=0,
        le=100000
    )
    est_gsd_mm: Optional[float] = Field(
        None,
        description="The estimated ground sample distance of the image in mm.",
        gt=0
    )
    orientation: Optional[Literal[*ORIENTATION_LIST]] = Field(
        None,
        description="The orientation of the image."
    )
    channels: Optional[float] = Field(
        None,
        description="The number of channels in the image.",
        ge=1,
    )
    blur_score: Optional[MLOutput] = Field(
        None
    )
    pct_pixel_over_saturation: Optional[float] = Field(
        None,
        description="The percentage of pixels that were over saturated.",
        ge=0,
        le=100
    )
    pct_pixel_under_saturation: Optional[float] = Field(
        None,
        description="The percentage of pixels that were under saturated.",
        ge=0,
        le=100
    )

    model_config = ConfigDict(
        extra='forbid'
    )


class SyntheticImageProperties(BaseModel):
    """
    Values associated with Synthetic Images
    """
    model: Optional[str] = Field(
        None,
        description="The model of the synthetic image."
    )
    seed: Optional[int] = Field(
        None,
        description="The seed used to generate the synthetic image."
    )
    noise: Optional[float] = Field(
        None,
    )
    model_config = ConfigDict(
        extra='allow'
    )


class AgImageModel(BaseModel):
    """
    All the approved values to be captured about Images of Ag Data.
    """
    path: Optional[str] = Field(
        None,
        description="The path to the image"
    )
    id: str = Field(
        ...,
        validation_alias=AliasChoices('image_id', 'id'),
        description="The Unique ID of the image, should be the image name, by default UUID4."
    )
    device: Optional[str] = Field(
        None,
        description="The type of device that is collecting the images, mobile, auxillery, or drone."
    )
    type: Optional[Literal[*IMAGE_TYPE_LIST]] = Field(
        None,
        description="The type of image it is: original, augmented, synthetic."
    )
    source: Optional[str] = Field(
        None,
        description="The path to the file the img was generated from, if there was one."
    )
    protocol_properties: Optional[ProtocolProperties] = Field(
        None
    )
    trial_properties: Optional[TrialProperties] = Field(
        None
    )
    camera_properties: Optional[CameraProperties] = Field(
        None
    )
    location_properties: Optional[Location] = Field(
        None
    )
    acquisition_properties: Optional[AcquisitionProperties] = Field(
        None
    )
    image_quality: Optional[ImageQuality] = Field(
        None
    )
    agronomic_properties: Optional[AgronomicProperties] = Field(
        None
    )
    collection_properties: Optional[CollectionProperties] = Field(
        None,
        description="Collection level information, will only contain CollectionID"
    )
    synthetic_image_properties: Optional[SyntheticImageProperties] = Field(
        None
    )
    notes: Optional[List[Notes]] = Field(
        None
    )

    model_config = ConfigDict(
        extra='allow',
        json_schema_extra={
            "example": {
                "path": "/data/2025/trials/trial_101/images/img_5521.jpg",
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "device": "mobile",
                "type": "original",
                "protocol_properties": {
                    "name": "Standard Field Scout v2",
                    "id": "soybean_rust_protocol",
                    "url": "https://aglabs.open/protocols/v2/scout"
                },
                "trial_properties": {
                    "name": "drought_resistance_2025",
                    "id": "trial-2025-001"
                },
                "camera_properties": {
                    "make": "Samsung",
                    "model": "Galaxy S24",
                    "device_id": "phone-001-user-x",
                    "iso": 50.0,
                    "magnification": 1.0,
                    "camera_characteristics": "24mm wide angle"
                },
                "location_properties": {
                    "id": "loc-8821",
                    "name": "Field 7 - Row 10",
                    "latitude": 41.8781,
                    "longitude": -87.6298,
                    "elevation_m": 182.0,
                    "crs": "EPSG:4326",
                    "admin_level_0": "USA",
                    "admin_level_1": "Illinois",
                    "site": "Midwest Research Station",
                    "grower": "J. Doe",
                    "field": "F7"
                },
                "acquisition_properties": {
                    "date": "2025-07-15",
                    "time": "14:30:00",
                    "camera_height_m": 1.5,
                    "camera_angle_deg": -45.0,
                    "light_source": "natural",
                    "lighting_lux": 85000.0,
                    "setting": "field"
                },
                "image_quality": {
                    "capture_results": "success",
                    "exposure": 12.5,
                    "aperture": "f/1.8",
                    "iso": 50.0,
                    "height": 3000.0,
                    "width": 4000.0,
                    "channels": 3,
                    "pct_pixel_over_saturation": 0.1,
                    "pct_pixel_under_saturation": 0.0
                },
                "agronomic_properties": {
                    "crop_type": "soybean",
                    "growth_stage": "R3",
                    "soil_color": "dark",
                    "weed_pressure": "medium-low",
                    "irrigation_level": "none",
                    "tillage_type": "reduced",
                    "plant_health": {
                        "stressors": "drought",
                        "ranked_stressors": "1. drought, 2. insect"
                    }
                },
                "collection_properties": {
                    "id": "col-daily-scout-20250715",
                    "username": "scout_user_1",
                    "start_datetime": "2025-07-15T14:00:00",
                    "num_images": "50"
                },
                 "notes": [
                    {
                        "message": "Leaves showing signs of curling.",
                        "author": "field_technician"
                    }
                ]
            }
        }
    )
